website/__init__.py
from flask import Flask
import os
import logging
from prometheus_client import start_http_server, Gauge, Summary, Counter

# Configuration of environment variables
APP_NAME = os.environ.get('WSB_APP_NAME', 'wsb-app')
LOG_LEVEL = os.environ.get('WSB_APP_LOG_LEVEL', "")
APP_SECRET_KEY = os.environ.get('WSB_APP_SECRET_KEY', "super_extra_secret_key")

# Setting the logging level
if LOG_LEVEL.upper() == 'DEBUG':
    log_level = logging.DEBUG
elif LOG_LEVEL.upper() == 'ERROR':
    log_level = logging.ERROR
else:
    log_level = logging.INFO

# Configuration of log format and date format
log_format = '%(asctime)s %(levelname)s : : %(message)s'
date_format = '%Y-%m-%d %H:%M:%S'

# Configuration of metrics
VISITS_COUNTER = Counter('page_visits_count', 'Number of page visits', ['method', 'endpoint'])
API_CALLS_COUNTER = Counter('api_calls_count', 'Number of API calls', ['endpoint'])
API_CALL_TIME_LAST = Gauge('api_call_processing_time_last', 'Time spent processing last API call', ['endpoint'])
API_CALL_TIME_SUM = Summary('api_call_processing_time_summary', 'Time spent processing API calls', ['endpoint'])


def create_app():
    app = Flask(__name__)
    
    logging.basicConfig(level=log_level, format=log_format, datefmt=date_format)
    

    from .views import views
    app.register_blueprint(views)
    app.secret_key = APP_SECRET_KEY
    
    return app

website/views.py
import locale
import time
import requests
from flask import Blueprint, render_template, request, current_app, flash
from . import VISITS_COUNTER, API_CALLS_COUNTER, API_CALL_TIME_LAST, API_CALL_TIME_SUM

views = Blueprint("views", __name__)

# Displaying the homapage
@views.route('/')
def home():
    VISITS_COUNTER.labels(method="GET", endpoint="/").inc()
    return render_template('home.html')

# Displaying API data
@views.route('/dane-o-zamowieniach', methods=['GET', 'POST'])
def procurments():
    VISITS_COUNTER.labels(method="GET", endpoint="/dane-o-zamowieniach").inc()
    url = 'https://tenders.guru/api/pl/tenders'
    
    # Handling navigation to the next pages
    if request.method == 'POST':
        page = request.form.get('page')
        params = {"page": f"{page}"}
    # Handling navigation to first page
    else:
        params = "1"
    
    
    
    start_time = time.monotonic()
    allData = requests.get(url, params=params)
    end_time = time.monotonic()
    
    if(allData.status_code != 200):
        flash('Błąd w odpowiedzi od API', category='error')
        current_app.logger.error(f"Error in the API response for page number {page}. Response code: {allData.status_code}")
        
        return render_template('procurment.html')
            
    else:
    
        allData = allData.json()
        response_time = end_time - start_time
        API_CALL_TIME_SUM.labels(endpoint=url).observe(response_time)
        API_CALL_TIME_LAST.labels(endpoint=url).set(response_time)
        API_CALLS_COUNTER.labels(endpoint=url).inc()
        
        currentPage = allData['page_number']
            
        # Extracting from the entire JSON file a list of objects describing individual orders
        data = allData['data']
        for proc in data:
            proc['awarded_value_eur'] = format_number(proc['awarded_value_eur'])
        
            
        return render_template('procurment.html', data=data, currentPage=currentPage)

# The function used for formatting numbers to make them easier to read
def format_number(num_str):
    
    if '.' in num_str:
        integer_part, decimal_part = num_str.split('.')
    else:
        integer_part = num_str
        decimal_part = "00"
    
    
    integer_part = integer_part[::-1]
    integer_part = " ".join([integer_part[i:i+3] for i in range(0, len(integer_part), 3)])
    integer_part = integer_part[::-1]
    
    return f"{integer_part},{decimal_part}"




# Displaying order details
@views.route('/details/<int:id>')
def details(id):
    API_CALLS_COUNTER.labels(endpoint="https://tenders.guru/api/pl/tenders/id").inc()
    VISITS_COUNTER.labels(method="GET", endpoint="/details/").inc()

    current_app.logger.info(f"Processing details for tender ID: {id}")
    
    url = f'https://tenders.guru/api/pl/tenders/{id}'
    
    start_time = time.monotonic()
    data = requests.get(url).json()
    end_time = time.monotonic()
    
    response_time = end_time - start_time
    
    API_CALL_TIME_SUM.labels(endpoint="https://tenders.guru/api/pl/tenders/id").observe(response_time)
    API_CALL_TIME_LAST.labels(endpoint="https://tenders.guru/api/pl/tenders/id").set(response_time)
    
    data['awarded_value'] = format_number(data['awarded_value'])
    data['awarded_value_eur'] = format_number(data['awarded_value_eur'])
    
    return render_template('details.html', data=data)

# Health check endpoint
@views.route('/health-check-endpoint')
def health_check():
    VISITS_COUNTER.labels(method="GET", endpoint="/health-check-endpoint").inc()
    return "It works"

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
  
  <div class="top-header py-4">
    <div class="container text-center">
      <h1>Zamówienia w Polsce</h1>
    </div>
  </div>

  
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark bg-gradient">
    <div class="container">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="/" class="nav-link">Strona główna</a>
        </li>
        <li class="nav-item">
          <a href="/dane-o-zamowieniach" class="nav-link">Dane o zamówieniach</a>
        </li>
        
      </ul>
    </div>
  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} 
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
    </div>
  {% endfor %} {% endif %} {% endwith %}
    
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

website/templates/details.html
{% extends 'base.html' %}

{% block title %}Szczegóły-{{data['id']}}{% endblock %}

{% block content %}
<div class='container'>
    <br>
    <table class="table">
        <thead>
          <tr>
              <th>Właściwość</th>
              <th>Opis</th>
              
          </tr>
        </thead>
        <tbody>
            <tr class>
                <td class="col-sm-3 align-middle">Id zamówienia</td>
                <td class="col-sm-9 text-break">{{ data['id'] }}</td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle">Data zamowienia</td>
                <td class="col-sm-9 text-break">{{ data['date'] }}</td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle">Data dostawy</td>
                <td class="col-sm-9 text-break">
                    <div class="accordion accordion-flush" id="accordion1">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="flush-headingOne">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                              {{ data['deadline_date'] }}
                            </button>
                          </h2>
                          <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                            <table class="table">
                                <tr >
                                    <td>Czas oczekiwania w dniach</td>
                                    <td>{{ data['deadline_length_days'] }}</td>
                                </tr>
                                <tr>
                                    <td>Czas oczekiwania w godzinach</td>
                                    <td>{{ data['deadline_length_hours'] }}</td>
                                </tr>
                            </table>
                          </div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle">Tytuł</td>
                <td class="col-sm-9 text-break">{{ data['title'] }}</td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle">Opis</td>
                <td class="col-sm-9 text-break">{{ data['description'] }}</td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle">Wartość zamówienia</td>
                <td class="col-sm-9 text-break">
                    <div class="accordion accordion-flush" id="accordion2">
                        <div class="accordion-item">
                          <h2 class="accordion-header" id="flush-headingTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                              {{ data['awarded_value'] + " " + data['awarded_currency'] }}
                            </button>
                          </h2>
                          <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                            {{ data['awarded_value_eur'] + " EUR"}}
                          </div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr class>
                <td class="align-middle text-center fw-bold" colspan=2>Dostawcy</td>
            </tr>
            {% for awarded in data['awarded'] %}
            <tr class>
                <td class="col-sm-3 align-middle">Nazwa dostawcy</td>
                <td class="col-sm-9 text-break">{{ awarded['suppliers_name'] }}</td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle">Data</td>
                <td class="col-sm-9 text-break">{{ awarded['date'] }}</td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle">Id dostawcy</td>
                <td class="col-sm-9 text-break">{{ awarded['suppliers_id'] }}</td>
            </tr>
            <tr class>
                <td class="col-sm-3 align-middle"></td>
                <td class="col-sm-9 text-break"></td>
            </tr>
            {% endfor %}
        </tbody>
      </table>    
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Strona główna{% endblock %}

{% block content %}
<br>
<h1 class="display-4 text-center mt-5 fw-bold">Witam w aplikacji do przeglądania zamówień w Polsce</h1>
<br>
{% endblock %}

website/templates/procurment.html
{% extends "base.html" %}
{% block title %}Dane o zamowieniach{% endblock %}

{% block content %}
<div class="text-center">
    <h1 class="">Dane o zamówieniach</h1>
    <br>
    <h3>Strona {{currentPage}}</h3>
    <br>
    <div class="container">
        <table class="table">
          <thead>
            <tr>
                <th>Id zamówienia</th>
                <th>Tytuł zamowieniach</th>
                <th>Data zamówienia</th>
                <th>Kwota zamówienia w EUR</th>
            </tr>
          </thead>
          <tbody>
            {% for row in data %}
              <tr>
                <td><a class="text-decoration-none text-dark fw-bold hover-link" href="{{ url_for('views.details', id=row['id']) }}">{{ row['id'] }}</a></td>
                <td>{{ row['title'] }}</td>
                <td>{{ row['date'] }}</td>
                <td>{{ row['awarded_value_eur'] }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      
      <div class="container d-flex align-items-center justify-content-center">
        <form method='POST'>
          <div class="d-flex justify-content-between mb-3 w-100" style="max-width: 250px; margin: 2px">
            <label for="page" class="form-label">Numer strony</label>
            <input type="page" class="form-control" id="page" name="page" placeholder="{{currentPage}}" style="max-width: 50px;">
            <button class="btn btn-primary mw-100" type="submit">Idź</button>
          </div>
        </form>
      </div>
      
</div>

{% endblock %}